name: Build Truct and Release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v4
            -
                name: Setup Go 1.24.5
                uses: actions/setup-go@v5
                with:
                    go-version: '1.24.5'
            -
                name: Install hub
                uses: geertvdc/setup-hub@master
            -
                name: Build the bootstrap binary
                run: go build -o build/debug/truct src/args.go src/program.go src/main.go
            -
                name: Build the release binaries
                run: ./build/debug/truct do
            -
                name: Create a release
                run: |
                    set -x
                    assets=()
                    for asset in ./build/release/*; do
                        assets+=("-a" "$asset")
                    done
                    tag_name="${GITHUB_REF##*/}"
                    hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}