name: Build Truct and Release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v4
            -
                name: Setup Go 1.24.5
                uses: actions/setup-go@v5
                with:
                    go-version: '1.24.5'
            -
                name: Build the bootstrap binary
                run: go build -o build/debug/truct src/args.go src/program.go src/main.go
            -
                name: Build the release binaries
                run: ./build/debug/truct do build ${{ github.ref }}
            -
                name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: Version ${{ github.ref }}
                    draft: false
                    prerelease: false
            -
                name: Upload Release Assets
                id: upload-release-assets
                uses: dwenegar/upload-release-assets@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    release_id: ${{ steps.create_release.outputs.id }}
                    assets_path: build/release